apiVersion: v1
kind: Service
metadata:
  name: my-app-nodeport
spec:
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31404  # Optional; if omitted, Kubernetes will assign a port
  type: NodePort
