apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: cont1
          image: nginx
          volumeMounts:
            - name: test-secret
              mountPath: "/opt/secret"
          ports:
            - containerPort: 80
      volumes:
        - name: test-secret
          secret:
            secretName: mysecret
