apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: cont1
          image: nginx
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
          volumeMounts:
            - name: myapp
              mountPath: "/opt/jenkins"
            - name: hostapp
              mountPath: "/etc/hostpath"
        - name: cont2
          image: ubuntu
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
          volumeMounts:
            - name: myapp
              mountPath: "/etc/kubernetes"
            - name: hostapp
              mountPath: "/etc/hostpath"
      volumes:
        - name: myapp
          emptyDir: {}
        - name: hostapp
          hostPath:
            path: /path/on/host/machine  # Change this to the desired directory on the host machine
            type: Directory  # The type can be Directory, File, or Socket, depending on your use case

